In [1]:
import numpy as np

In [2]:
X = np.array([[1, -3, 8, 1], [2, 4, 8, 1], [4, 3, 2, 1], [-1, 6, 0, 1], [2, -3, 4, 1]])

In [3]:
y = np.array([1, 4, 2, 6, 4])

In [4]:
X_transpose = np.transpose(X)

In [5]:
X_transpose_X = np.dot(X_transpose, X)

In [6]:
X_transpose_y = np.dot(X_transpose, y)

In [7]:
lambd = 1.5

In [8]:
identity_matrix = np.eye(X_transpose_X.shape[0])

In [9]:
X_transpose_y

array([19, 43, 60, 17])

In [10]:
lambd*identity_matrix

array([[1.5, 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. ],
       [0. , 0. , 1.5, 0. ],
       [0. , 0. , 0. , 1.5]])

In [11]:
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.linalg.inv(lambd*identity_matrix + X_transpose_X).shape

(4, 4)

In [13]:
wRR = np.dot(np.linalg.inv(lambd*identity_matrix + X_transpose_X), X_transpose_y).tolist()

In [14]:
type(wRR)

list

In [45]:
x0 = [2, -5, 3, 1]

In [46]:
x0_transpose = np.transpose(x0)

In [47]:
sigma2 = 3

In [48]:
covar_sigma = np.linalg.inv(lambd*identity_matrix + (X_transpose_X)/sigma2)

In [51]:
entropy = (sigma2 + np.dot(np.dot(x0_transpose, covar_sigma), x0))

In [52]:
np.dot(np.dot(x0_transpose, covar_sigma), x0)

1.7939000793960957

In [23]:
np.dot(x0_transpose, covar_sigma)

array([ 0.18301595, -0.22670164, -0.05020987,  0.44498959])

In [ ]:
https://stackoverflow.com/questions/16468717/iterating-over-numpy-matrix-rows-to-apply-a-function-each